---
- name: Disable system's dhcpcd because we're running our own dhcpd with supervisor
  service:
      name: dhcpcd
      state: stopped
      enabled: no

- name: Make sure DHCP server is installed
  apt:
    name: isc-dhcp-server
    state: installed

- name: Make sure DHCP service is *not* running
  service:
    name: isc-dhcp-server
    state: stopped
    enabled: no

- name: configure DHCP server interfaces
  template:
    src: isc-dhcp-server_defaults
    dest: /etc/default/isc-dhcp-server
    owner: root
    mode: "0644"

- name: configure DHCP server network
  template:
    src: isc-dhcp-server_config
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    mode: "0644"

- name: configure supervisor to manage DHCP server
  template:
    src: dhcpd_supervisor.conf
    dest: /etc/supervisor/conf.d/dhcpd.conf
    owner: root
    mode: "0644"
  notify: reload supervisord
