---
- name: set hostname
  hostname:
    name: "{{hostname}}"

- name: disable default users
  user:
    name: "{{item}}"
    state: absent
    remove: yes
  with_items:
    - ubuntu
    - pi

- name: install runtime dependencies
  apt:
    name: "{{item}}"
    state: installed
  with_items:
    - avahi-daemon
    - python3
    - wpasupplicant
    - wireless-tools
    - supervisor
    - python3-venv
    - python3-dbus
    - libffi-dev
    - libssl-dev
    - lighttpd

- name: available interfaces directory
  file:
    path: /etc/network/interfaces.available
    owner: root
    group: root
    mode: "0755"
    state: directory
  tags: wlan

- name: configure network interfaces
  template:
    src: "{{item.src}}"
    dest: "/etc/network/{{item.dest}}"
    owner: root
    mode: "0644"
  when: ploy_wlan0 is defined
  with_items:
    - src: interfaces
      dest: interfaces
    - src: interfaces_dhcp_wifi
      dest: interfaces.available/interfaces_dhcp_wifi
    - src: interfaces_setup_wifi
      dest: interfaces.available/interfaces_setup_wifi
  notify:
    - restart wlan0
    - restart wlan1
    - restart avahi
  tags: wlan

- name: ensure document root
  file:
    dest: "{{frontend_document_root}}"
    owner: "{{build_user}}"
    group: "{{run_user}}"
    mode: "0755"
    state: directory
  become: yes
  tags: www

- name: configure lighttpd
  template:
    src: lighttpd.conf
    dest: /etc/lighttpd/lighttpd.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart httpd
  tags: www

- name: configure frontend website
  template:
    src: senic_hub.conf
    dest: /etc/lighttpd/conf-available/senic_hub.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart httpd
  tags: www

- name: enable frontend website
  file:
    src: /etc/lighttpd/conf-available/senic_hub.conf
    dest: /etc/lighttpd/conf-enabled/senic_hub.conf
    owner: root
    group: root
    mode: "0755"
    state: link
  notify: restart httpd
  tags: www

- name: announce web UI via avahi
  template:
    src: hub_service.xml
    dest: /etc/avahi/services/hub.service
    owner: root
    mode: "0644"
  notify: restart avahi
  tags: avahi

- name: Make sure the hostname is available for local commands (i.e. sudo)
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: '{{hostname}}$'
    line: '127.0.0.1  {{hostname}}.local {{hostname}}'
  tags: avahi

- include: dhcp.yml
  tags: dhcp
  when: ploy_wlan0 is defined

- name: allow run user to setup wifi
  template:
    src: sudo_nuimo_wifi
    dest: /etc/sudoers.d/010_nuimo_wifi
    owner: root
    mode: "0755"
    validate: visudo -cf %s
  when: ploy_wlan0 is defined
  tags: wifi

- name: configure supervisor (enable RPC interface)
  lineinfile:
    dest: /etc/supervisor/supervisord.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^\[inet_http_server\]$', line: '[inet_http_server]' }
    - { regexp: '^port=127.0.0.1:9001$', line: 'port=127.0.0.1:9001' }
  notify: restart supervisor service

- name: configure supervisor programs
  template:
    src: "{{item}}_supervisor.conf"
    dest: "/etc/supervisor/conf.d/{{item}}.conf"
    owner: root
    mode: "0644"
  with_items:
    - scan_wifi
    - wifi_setup
    - device_discovery
  notify: reload supervisord
  when: ploy_wlan0 is defined
  tags: wifi


